name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install flet
      - run: flet build web
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build/web
