name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install flet
      - run: flet build web
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build/web
